import { createSlice } from '@reduxjs/toolkit';
import Employee from '../../types/employee.ts';

const initialState: Employee[] = [
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-02-03',
    startDate: '2019-03-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-02-03',
    startDate: '2019-03-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Raul',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
  {
    firstName: 'Juan',
    lastName: 'Gonzaliz',
    dateOfBirth: '2009-05-05',
    startDate: '2019-05-05',
    city: 'Madrid',
    state: 'Madrid',
    street: '124 rue de Madrid, Madrid',
    department: 'Madrid',
    zipCode: '16742',
  },
];

export const employeeSlice = createSlice({
  name: 'employee',
  initialState,
  reducers: {
    addEmployee: (state, action) => {
      state.push(action.payload);
    },
  },
});

// Action creators are generated for each case reducer function
export const { addEmployee } = employeeSlice.actions;

export default employeeSlice.reducer;
